# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: blocky
    namespace: blocky
spec:
    interval: 15m
    chart:
      spec:
        chart: blocky
        version: 18.9.0
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    timeout: 20m
    maxHistory: 3
    driftDetection:
      mode: warn
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    values:
      global:
        stopAll: false
      TZ: America/Los_Angeles
      defaultUpstreams:
        - tcp-tls:1.1.1.1:853
        - tcp-tls:1.0.0.1:853
      k8sgateway:
        domains:
          - domain: "${BASE_DOMAIN}"
            dnsChallenge:
              enabled: false
        forward:
          enabled: false
          options:
            - name: tls_servername
              value: cloudflare-dns.com
              primary: tls://1.1.1.1
              secondary: tls://1.0.0.1
      service:
        dns:
          loadBalancerIP: "${BLOCKY_IP}"
          type: LoadBalancer
          integrations:
              metallb:
                enabled: true  
        dot:
          loadBalancerIP: "${BLOCKY_DOT_IP}"
          type: LoadBalancer
          integrations:
              metallb:
                enabled: true
      cnpg:
       main:
         enabled: false