# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nzbget
    namespace: nzbget
spec:
    interval: 15m
    chart:
      spec:
        chart: nzbget
        version: 24.2.0
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            hosts:
              - host: nzbget.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              homepage:
                enabled: true
                group: "Documents & Files"
                href: https://nzbget.${BASE_DOMAIN}
                widget:
                  custom:
                    enabled: false
                    url: http://nzbget.nzbget.svc.cluster.local:10057
                    key: "${HOMEPAGE_NZBGET_KEY}"
        persistence:
          downloads:
            enabled: true
            path: "${NZBGET_DOWNLOAD_PATH}"
            mountPath: "/downloads"
            server: "${SCALE_SERVER_IP}"
            type: nfs
        config:
          volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true                            
            src:
              enabled: true