# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sabnzbd
    namespace: sabnzbd
spec:
    interval: 15m
    chart:
      spec:
        chart: sabnzbd
        version: 21.9.5
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    driftDetection:
      mode: warn
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: sabnzbd
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            ingressClassName: internal
            annotations:
              nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
              nginx.ingress.kubernetes.io/auth-signin: https://auth.${BASE_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
              nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
              nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
            hosts:
            - host: sabnzbd.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              homepage:
                enabled: true
                group: "Documents & Files"
                href: https://sabnzbd.${BASE_DOMAIN}
                widget:
                  custom:
                    url: http://sabnzbd.sabnzbd.svc.cluster.local:10097
                    key: ${HOMEPAGE_SABNZBD_KEY}
              traefik:
                enabled: false
        persistence:
          config:
            volsync:
              - name: config
                type: restic
                credentials: s3
                dest:
                  enabled: true                          
                src:
                  enabled: true
          downloads:
            enabled: true
            path: "${SABNZBD_DOWNLOAD_PATH}"
            mountPath: "/downloads"
            server: "${SCALE_SERVER_IP}"
            type: nfs
        workload:
          main:
            podSpec:
              containers:
                main:
                  env:
                    SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd.${BASE_DOMAIN},sabnzbd.sabnzbd.svc
