apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Xs51q5wsu6tepincxOumTM3rz+EdZZBF+57i0+oWhBJZD6SCvcFqcCpBMHpFXhTziicSJ9UMrn07INfEomel2w6XqujC3gw9T7vYU751CRSBsLGxHKpZ3J5vijBaoXpAgxcCcIPo9SeVbNFg4+OJXVgqhNVihgMVM7ZlhMyJPNoR1Terw2uE6SNL5yLLNN/P2CQ1ftlNOawELdOo6NA/Ra9P8xPpJOpJ5KIuZMP9pYsIUzXo07JPp4rIKE9QVJV0neWUMfCWMuzOCi6qPgyqUyX8vUO4JlD54pZNT0V5nD7SMq8D3DxMj89vvip0D/xTebeZOBvmN27olVV7WUtZP+WXx9SCdaYQiUD2PhJmmUE7M4NnSZwKOWXg1081csAV,iv:W3iAPcIPc0pKx0VwSuJWL7yO5E5ohfAWqQf4waD3rX4=,tag:x7d9v0cQa9Mxku64ZR1yKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QBrEKCAOkXwcDhEzDRzuU6Y8JU15+klXhl3FWbhW/usJuSSescRZd6l2K9+b/YQdD84vPoswjhjR1fp3bu6PvYEDQtH5CjD0/30JeoXBvsfX57yWdU59+FWUilVA5FNjR+j3doqVDah3OMBwCqfkF5AMEEHvBAB+yq0VvuSYg9ukb6UTlQLv9LkVScBCrck7WZSulg7X0u9skzirbYrnDLVMWwuVnTReHQO8hOWB+LCbJB54WqQ+CSKpsDjYc7a6C8DOB1D8Y+EVTeBIEg==,iv:9yai4h4noYhB9KGY784vtxl/GlNZqN+zvs09odna8mo=,tag:Y6L8EPmEz1Ga67jHYHj/wg==,type:str]
    known_hosts: ENC[AES256_GCM,data:w9AnEywkMXw2ZcN+1Mk7p8rMUx7pw1Nz6zz06kYZzH+E6OOWuUyyMMGMy9hPvVac8pyxHArmCt2XfFEjsvTnqLNWdqOsDkjEI96UaTpabLqPByXXYtMLGydE1dtnGEsqOpYDnCtDOXIVfS6G7yd4eaBDPet0nIvD+ZWAaQP2fwp3YwL0Uqnamdl12h0o7Mphl3dGekYAQQNo5sB1HN7geJ3rsW8l8Y3GPuWE,iv:QH9Kr5IuzsLnCWm79eASfpvmfQARAuw6iDiv0bJ3pJ4=,tag:M6uezzHNUgAEng5cma4y/Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZTZRZzQwOXN5cG0zUnFm
            cFZBM01PcllIc0RsM0lrdmhOYnJDVHlNdmdZCnNxNU1EZTBGdDlYYXh0czFyNSsz
            cENVWnpsSlMzSTBpZUtUYVhiREEwYVkKLS0tIFByMStvRWRJM1FzZjgwSndFRzdK
            clR2aHRUNVRlRWJIdDRmOVpETWZuTlkK+L+d2tMjCrDFmvoDa/+WO2mSR6kowENr
            dy/2jDwm3pTxhIjh000grwVrTU71TTSzqOdmjoFvsmmFd4qzleF7dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T01:28:07Z"
    mac: ENC[AES256_GCM,data:HX7I1fYKOXNupRNOf9j4uvpc7ETlgm4TNCuyDkivrlwD8IYCIHhcg+/+4uca6y6u7l9w3prWk+B8RP4v++Mg7t1Q9IOZbx9V1e2FDFAEWcSijIZ91nikcjnVYPV4U/5EdJTLK/NUzK3KIXoT2z32w83I7PJq+AQfL+hwYjNNQvw=,iv:H0XDHDWRi/3HNWieEk2HulUKDewD3M9eIJlPBscwKTs=,tag:3XWGYMMy9S3X0GY0iBsa+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
