apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: |
        -----BEGIN EC PRIVATE KEY-----
        MIGkAgEBBDBQ04Ajj5sqbEwAq6Pw3gIlvFSsMjLjJgUwt/tqRbDz1C5SQ5oB5oam
        Bl4kplKy3X2gBwYFK4EEACKhZANiAARK+fTROicokEZcI3uEngvBgjP0978bh4Sg
        f61U5MNOF3V8jaF+fAh9WD93hX7t6NYeEQLYjefiDBDEIsmYKmUrngCS4tbItaBQ
        GHinxFgTML+H7f7GKGZQ/VxsB1NTqL0=
        -----END EC PRIVATE KEY-----
    identity.pub: |
        ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBEr59NE6JyiQRlwje4SeC8GCM/T3vxuHhKB/rVTkw04XdXyNoX58CH1YP3eFfu3o1h4RAtiN5+IMEMQiyZgqZSueAJLi1si1oFAYeKfEWBMwv4ft/sYoZlD9XGwHU1OovQ==
    known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
type: Opaque
