apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IDRP2akydXPJ4zAxiTtcJLUj2HrQDr/uoAMmxB8XPSue84iFIIjBJ3mVN2i5KYhpmtg0s/LVmz9xsBgQOnBEzCkh1Pk5PnnIK5AeBPNURSDdXoL9yxnm3YbZeEGGXS4xX2B7RtTUZXi/LzdeP2qla5L3PztUKih+0p0sBfsrYE4S9YuVwVTogDComN+kijlcABjeDIedPVS9lnUqv9oQHF2a1Dxp1Eqy+PGGyDbEpeEiRd8N6kI3JPRKWC5R4UFuRRoHV5XEt8mlUTNLq65tRYxyMJuzyKCjFy/nZQse3YxQG1rT78LlgJ2+3shqHZccTln4V5av+if18rnV3PAplcbU+2eifNoKjT7DkY/GVYUDZg0qtZrAGahHG/IcgMD7,iv:isdIGMwmQJ4IZ7TUrMU21uYWsLZeJG92JPMvCIQv99U=,tag:1LQ7oxcufNeqIRLLAexv2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:rkrsoC89d9NE48RDYASKhZlmbWHUSmihEUln3hOuZhXoIevVrPUJaiGLSuCtkZV7vtaXptzBlFvCubzrsH8eH6LrXB421iI0pjx+u/jgC7FD0xJEfTDg3kWsQHLBbIMBfNlqAxvd7DkhcbEzTWXsWCLcI1W0yuFpa5G4ImQD18lF/fQWG9G5FSCLYPyVDidUusYln0JeXJrPruOgUEFKgUCVxMbMIy0AjJaKaZ1gDpxnDtut9Z/1k2ReGxaITFr38KwpCarLJ4Fr9IRLAg==,iv:V95YPNG1dwy/oTlhvm8vqCS6fll/lEIfZVqxu1gmYy8=,tag:EQ3bJa4gSh6U11ZC9dQ0NQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:juOXRKEpv9HEh+RxKt5mVXIXUUhPtqosHN8ujbdqijuFvXgEc2L8RiNE5s7m1TU1VMn5yFzlbfvHDj9ZEFsvj1yRr5sLpuYoHYKC2n5SV4sZCzVrGQDzKl6mbOujOAqcelshGl1YXmbbS3MRRgh1B1kx2BGZcsT7KKxz+o5iBFAmrtpli+kW3WJZepTItNIsUdnykQ4hwO3hbN0nt1kAhPUTREkQTnbJQgJB,iv:Gd66CPMh5eiBIWz3byjjZkiWjA+CC5cdG9GT5VwAe5I=,tag:U9zeDQ0kibQIQ/WOE8YLpA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeDIrTmJuVVhBQW9TZGhO
            OWNyOUo0engyYkdFVWNYVjYvNEpDY0dqMDE4CnBvdDV5azFYUlpPQi9xV0N0OUJo
            dFlVMi9yNDRucnR3YkZpaDJWNExtQWMKLS0tIEl4L0s0RG1xQnc2a2xNMFFySXZx
            eDM5VWx4Q2lNV2F0d2Zldk1zYUlaSGcKOSwiF5v05tG544/xrGucDPkUwmCJ/UtH
            vuG8/eOryBy8md5P87XLRZvNPuG9LzbgPbAKRp0nZSsM0cgfyCAYZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T05:07:13Z"
    mac: ENC[AES256_GCM,data:grSCiFocRumEBjVWDoWlGdUsHK1WCYd9vzfZHmo2srP9UoQp0IloD0H7qMAYr5HtDAU9Tdo6hGQe7HistjR1Ce6fcnOjO+khy+dN5MYSVO5MMXTlN/ql1gM64zu+R5FgAA/I2cC9g4B4ES19rql/0ieDVBTPnzEAnbaDwjl0n2U=,iv:mVfi82w29HJ7oCqci/pveEE1Y7zQgtOHW2YijvYOoZM=,tag:lTna8dEElzH5yLLKbghLvg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
