apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7r4b8X6cqQG6tjR6JXnRqQkkkUeAxvajc7lOeido8JHMF9AE+l6YhKnQohvx17nuN2Qw1qYAopj5bxbewW9JLpDBkQ5Kpm0nNSorSXvVG0soCE9YKdhkBuSdx0RN2wbBM8cyH7EB+Invg/jmKfwTmhgfXUKXJnBLHeTtur9yZOH/ILJmyWwEhrevkXpAE9g0WwuUpH408ULfyOfqGIPV3RyB8PtGygjyWrvaLu/dWMrdNBJD7R5+3DuMvMlXcuG+vxwrJkI0fbnN8YOwrZmOmd1I5LhQxnI7lcvwbGw7A2QkuB25QwkN34W3ogV6T0yHAW/fxW+7U0uI9Qe/LdF5/uTblLoDc6ky0BXuZODb1fGIN4MASY6IBpBgplFEO6OV,iv:TFKdZRMsF2h+ssLPjjIp3tMdWZ9Ro61hZXXDh+GvwSw=,tag:KfgglENXpymfvSN4+hhU/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:H86qDeuGyPynU3jsTai1pI4mYemUMtQ92AIwtLVJGE/vi25nxrvzjTO5rvaoqjsExKuWvL45eHSgNaEn51aD/6JRluF/MSO/Xlg6A8euyInoOuyfwcDCC40MtwTxuziLL83Bog7deTsyifPF784sNc52IWOHSkK2qdlBP18YjtCF5Wje+tfGK6rAwBb8eY30vuehBcnKe+NTht7vlWK+dQhnTiFcT1ccBfQpVUbvBtIhv0dZCwhBUeR9owMkXDLuSvMu8qHtoef0gs5hMg==,iv:K2Wfv2lxrRgd21lJePkhtQO7GNOZtsGelHPAt2G+h0s=,tag:RDUZyky4nJgVsK3IZAae5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:6X2NtaQPsMN6heHfdXUzICNfm/oBAj6+xWQkog7tAQnov18g68Coow43OXvkbZiESIiAI+TSRjH98ycGgeT3/JCDwT3jtncj3ABVlXKs/K2Qdh4Xn2OuX4Uwlj5/2Fy2izq+wyE8BndAr3xR1wuws5SO+UOC8bMIBgWh3FChj5qs9UBF7pFN1YnUpIYqe9Qv44KuBkL54FN0LaSbsYJpigh2j9NUS1EKojJ9,iv:d7L/31uf7WmMBZC4dAJFi4sAyqUPkQ+IOgXHEfzPAcQ=,tag:odYkbT48C73fWqJl8hSi9Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV3ZkMFRhRmozN2lrYndi
            VTNkYkdPcVR3UmRTT0YycVI2RzZROGhPTEVvCkZUcHl4Q3p4WVFJQk9zR3RNa1l0
            eSs1WlZVRGdvWHNsVTlBUml5ZTUvdVEKLS0tIFV6RVBtV1NMaTk0L0xBRDM0d2lP
            eWZSU1ptdG1sUTgzVnR3aktQL1FFSUUK1I2I4NtGF/YD5mzWImHta7AV1hBENImo
            lYXvQ2hFlnD7RL89jn9SO7m5NbfrwSyde8QIheOsnO9NtGAkQwcmYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T07:05:06Z"
    mac: ENC[AES256_GCM,data:7ZHcrxj93sk4hcXnOZrySwPYdA5u6mNC0tmP1+LDQNYhmYOnOPA5K8ysY1hHtXlFimMBe9RquGSOkWQtNf8M38AMvf+/9oYUCP4LAPO/O4u/vPQNTUDNcP6k2BlqHs7DHgz//4aW5CfLpslLbuenNaWfZbZl+YBNZMnP7ve+nVk=,iv:6BQTK1r/AyMlfhPXStjUCqAe5lDnZXQ5P48YLcIWmjc=,tag:GQ+DVj2l+R+eecFjDp4CHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
