apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1f9wmFD8SYEiyGDElVXkoER9kHV9uB5Mr5dWa0QZH3bYT2/kFiD4D5CxEEezX2h5XqUAAFG9S0Ur/clkILMfGlfYE6rn6sMoxnT2cx1y8mQ8rlvrdIxKD0QLgsB3t4t0qdsaJKp48MqFi5M1fXCWaPnFz3Y13xUlohWq+mLvKsH7UXzYuMKvsmyjhyyk2OlOQc3L/+mJYCxDsEQypoHWCpJA9Yp6tR2oeODWzDB9dSPn9gy/AJvYa+P3AS01cHOO2KGnJz5CNjn2rkkOKTb3qbXAbpxus9RUCZklFjieUoUcPYUNHwNrKRwo023V7DLN69E2VWVYniGa/BkUZKiwPmPwxQGg73LxrklNx3uVgiGzC0S40qhMLoAVrLVx9doQ,iv:zVuduBHv6lHUUGp2qDsZ8v2pXO3K09TSQXLdBAZDWlk=,tag:hwUYRlsnMYp8bY+mbzHviA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dwugRLqs//qUxbKR40hVzq+gPr2au55WNggGN2hpyBBF8dM6MZoxwFo1JTjh/p+OC+4NlXU+3ljki/RFME3RaniNWaiqC5nGRP6EKUZNo0bWPWSl9gcBmn8nfbzoDuVRfdAuIo0pjZPwRMLdPXZwfN6vm0lYGpJ6gFnrZU5Kll6JqLNT2LPa68mcw+qLvTfZHrzq7oemLsDD6lr4LeZL8ddMXDRGdK1rY/lYhhHFQ62+5PeZ24TwUAzlNOAjUIJMaNzAifJ91HFhWBI5/g==,iv:+T14qWfQztNQm0Dvd31OUn3sXA5/p+S7cBvQjxZkOiI=,tag:h++LeTpHo2lum+Phq4acHA==,type:str]
    known_hosts: ENC[AES256_GCM,data:52V+4dfPTa9O3loL4k4NIrUgqW6QKTiitdBx/PNkU0XT4XDVSwPwkAtugcs2byf6c5i3CAbEW+Zcw0mYs9aBSYYu83VSMHjYM4u/sguBjkUuUOGHWrO8NSLsbkMxfH9hL9tf3G29d4etnQ9K3QfbMN1Ddq7qp4o2QatwdgYI5UpMdoVkjNeKKLI14TJEYhqJpHfbpUb4RK1/xmwdyUv2wr03O2d5MNJMBxPy,iv:8oBPz0Z042NpwiDETVx/2LOieBCQEh7Tj8rYmv0H1tg=,tag:eMrrnJVtarCb6CaEXHdLGA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UTVLOEpMb0Q0TURGTEcx
            eGNrb0xyV3NId1QyTjJtdElydjdZaFUxclNrCnVDdlJrZlE1Rlk1MEFaMHc2d1N5
            V3UySmRFY0FnTm8vYXdsYzdqL2dmUkkKLS0tIGdNMjNrZGt4TzljMFJjTVBJemxp
            R3c4NTVmQnhEcXdaR2dJSHhnVWgvdEkKS0Q9I1Y3HaWZ6nKN3IfR628T3daPS916
            Dq/eRw9ikWzr4F2s8AN7GIDcf7qeHnVSFcjNs/I/Bo7neba5RVR8gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:05:29Z"
    mac: ENC[AES256_GCM,data:iFbomDML81xiQX+P16PwrVixFPK7YdSPNhdtBIUnh0P2Bttscpq5g/umMQLYmRcp2JSJgrz9NjlMRGWPpm7u2rj0ZrEN8/PMCsvgT3PMiORaVHoj9pIXjoKKMifNGbXi6LkzS6U8J9V5vFDW1sqPzt244P4QiO6Cbkn5N82k3W8=,iv:qAXN4daMoug0wmrDHc/b65XVSR9HFN7Nk3LMX6x9o68=,tag:/a4MxECJaNnZ+tfHPx2qrw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
