apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IZon9VClicbz09lP2CbybUJv/YqtFwlcOzX1wp2LbJ9si0mZfrCefkWWbC1fSy3A+fZx/Toyx3ticWjoNx1QSHCydvBduf9d55Qu7qFSx/CpzAsZtg3Ksx+We4cbUj5OuwgCzHszK595AvGvLxrfflcCIaBkvZbUwDG79MCnIUM6iKEhQ/xSNVcCooxunzq48e5Mgk6jx48gEqWRL46mVoROQpGGlKXOWQA5F9LEjxo//Lhn8Pn51KmZi9bduNR2GyDxLleDhfuGkjI1zqG8DC78sFVbD5Pav3N6+KtfQP436LoPpNyvRLD5Hs18s0mVntXfnTh/a/P6ME26/CIPNVspGTHwChxb1LxmB0wIKJrC0JdW+T6NA8Jg1Whcr9zI,iv:yjTb+vJC1Sb/IxopSaNh3ySri1LkNHrY//FmvSZ0Gr4=,tag:VkW437Xjmk6SvAmanhItGA==,type:str]
    identity.pub: ENC[AES256_GCM,data:bQJ+/KozoAOnhaYBZVBauDynj4ONfzacHq2X7Kqe/PsTSpsiBbOyO0+Cnc+sf9cQVgP6F+KHD+9i1i7YE7GRh9mBN2r71n58En7N7GDWPXF8FAohmcqUUafezopYy6+OD1LNam7MhdUakzCW5LTtpAXf7dGNdFm3B/9Ui5H1F1KxxQekuEynXXeisnPXI23iVWlIGHbbCTP4coXZdetePk8tAyWe38MzgZVMMva362u/IeP382OOXx/LbN5BGzRbLb6B7SUz8aJUKlOnpg==,iv:xpdewYbH6Kozq+8kg5ufywaG6/XRoEJOAWXqskbDBuU=,tag:SqJSuQKApwqYqDadsETGVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:RoXSYwYYdTrGygfCFWrM6TAHpYWN/l1Jc9jiwClh+FyjlP59vaAHqg0rysmIP+j/e5jyzZtPIAZ2T8EpXxoMj+isp/LU3rvG3xapYg75fuzq8RsM82bfwCsPWBC77WOZSYmxYOJAix4129ovjoNdms5meIp9qa+/aUykpz46gaxCHgWirRcXq+zNgB4gwRWEmcUqK3wBGp2lyDlC9vHRRdapyojrBt+JRsFZ,iv:tuByO73HawhGE60gUcDOqG5M8yjFaB1Z0SV5YD7AYtM=,tag:SiEJjwe+BvISbGQvERi6eA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkY1NHFuRHJXTFZrL0kw
            VWNMNW5lbkVPSTMzS1M2ZW8xRGlVTTJScGs4CjUrWDBLOGgrNzE2SFIrU0Y4Zlps
            ODZhRmJnajFpQmFBMDBYM3N5UkttaUkKLS0tIFFiUDBnSzA3QW1lS1ZqQk1vaWM4
            dnQyMXoxd3JrWFEzRlZuVFdWQTRxNFkKmcwrCEO5OG4Zn088uHDsG1L3QMwjlDMH
            a3BWGlUqg1S1FaTJUhQ4cmgYjxIpClAjX5UPqbO3LBSplH8YshXMiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T06:46:29Z"
    mac: ENC[AES256_GCM,data:kzhBswMuv4lQd1n1l0YXmBV1r3Z85DI1ehvta+eSxP/exdZLiFh4elSiOTqWya3zuQsioROig3hxguBeB/qLP0jpXUF/SfKLUVzMVH7hOV0eVX9kwk9G+Cjlwsom3DQP+d9JhjYOIru6cSv+VVSJipX3rrpMLgNU19vRvTBfiMc=,iv:zSDdByWPcE/axfZqtiOyVxLYK8k8+uw5yqOQ1cQVq1U=,tag:f6+BLWs+SCUJTLQV2h4iKg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
