apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Bb2wHoIuQxA/2+ywcNMzTB/b8BuUfrXnICvm9roOiiqV0G4ARLYejaX2sPQdbn0OMQQw3dPbhhsoN073SrxmXryzpSxEfzo5dH56sSa+6nHzN9SslEh9+63eJyV1zkQaYpiv7ewCXysoCpIyh6vJ2caktBmOx2Osa40Bntjk/u7PGJQ9XQ9HyYx4YiCTF4Zum0DG8PiFMdq+ypEdCxBoSVB69dboj1B5Nk8aMYPQxPDlqGTSQyR23n5QNzQQMaue6eXmtWj7E57b6YS4YW3ID2oX3Fly1mPNpw+awT8c2zyIvf/CEOj8V+jtt9EvkgSHAuZr0Ta0MmDNLOcYIQlzswpvKPFoay3If24KDWa18wrHYWmzncN42wJzYPdLACMv,iv:7hnml3Lf0oG4fvtRXmV6yxZxtWNiZziTONFdUtqIpBs=,tag:loa3NYAW8w3udR34pdrqYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dFNbRkKwwHmLE7emhorg4Yyq1gMzcLXnzEzURp+StEe1JXw5mqBUm6YNUMs48Z2C8kYBnYyY5loJEDbBG2X9LN3SKNZYIdnMVW4W0JMbnqmwzqnDRXaohyzLo7CXnlgu+fomk1wO/gk+gk5NzdNzmyJzP9ywLfpjBUKe6vnS+MWZ8B81vpu0G0HeaB9KAcbnPiocwZl+BcoSSD48RVLUqpJvhV1idrwNna01lwSvPy1bvjbeIM/N2BirsNpVxf16xtBz61B2LKKy1nYEIw==,iv:FiDqyudn2cL2owqZ7FCexJNeh6tlsRjG92fSBVC4g40=,tag:+gsqDLxHID0clCH0W11TeA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ua5RzcY/CZC+yVYShe8uVKx+FNLaqSJao5QLEUME5tbyVteZGGf891mfUBUVzDxS0/G6XkFH5Lra+qRsiKgRaKMVc/uqVXKFpWUH0C7tJUFs1UCEm7a3zc9qXnNvi69b3qSFivOVlaNZ/YCNCVtFvxK159usVzHoSgxFoO1s8f/m5WIXAW8JNnHD3iQC4AXWskehZyKQaqrGKzIw+m2HS7YBHgFOnBfmnbpT,iv:Ij0ztWy2/o/IQyJaVeI7bb1mzgxE2eJD3EzUmLK1I3M=,tag:bnV76eO+eNArtgpl+JAziw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3L0g5eE8yYWVRay96U1lB
            VVJuTWtFd0xyNHFZSG90NkZ6TlBpNUMvcEZzCmFZZVZWKzEzamdsNlRoNEkrUFNm
            bHh2TUxrbVY1dDd1azI1RWJybmFJMzAKLS0tIEdiTkdzcnBYaks4T3NhS0pCaHEv
            VC84WmU2V2JIUFBTdUlHakZiYmFUZzgKze0lOk7919PNEIGMUvq7fLNCsxIVnA5n
            l+PbeFQJm346iL/aKISPpkkIbnCMUFEKAHwfZW5SrrwiwE6H3O+thQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T05:51:57Z"
    mac: ENC[AES256_GCM,data:H5KLHi2Rws/NOdLa0aV7jAyO/XETilw+b3tWqXKL88bYzlANKE8tndJlNST8gEc+EN67JcQzhP2yIv2nSQGj6rE4n1tG6TKNSQuaLlszt8x1YDZoa0a1pYarsRJgSyzKTQ3d52uRBf7pexXJB/R5zkHCXa1VPUri7uuj+I/2QrA=,iv:EwIS8Y2C98xbYeLrwO1XtN1NhVskP0MS7FaKJ1fap0o=,tag:0oBbrqqNYQ3RzyTsI+BqVQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
