apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m+f3/ususe+xH8DvvzK4irF+S3vLkiVDkRklqRb2pVobjfRs/kEjYkt/8FjGvtw0j2n7YMQ8sOBrEfAU4F75lQhQLZ1ELJPAcJ2vlEbH5eLsY6qk0ForFT0G9frwzLjSWuN3HIa8r6F4r0h3vZQiY1n/1LZEgCPQhehkfmS6/ly5uWojthWbGYj+rl+N4173M39Qw/jVl3m4jDMUj9RDQY3iJI4mQ3HiDxj4tHBuDPROQlOH1Xb6i7ziURumpWdB5qmsTnVanR1cCJu+NTZuZvuymQaR5ITFGO7hAYNHsyiFRFl6UbxZ89E6d1muKzQMs+TriRn+XunnFo5PeMzIFB3qcblBAAlCZQM907i/DhYUflgnugXS+iw1C/fYy0wf,iv:S90zVAZ3TMEZyMPHbyLmsZLI9dz7N5BpcncNn1kmEXQ=,tag:ajnLX0XzeD0nMGEzi7R8hw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vy+iLeZWL2g5t1I5IgKGtYHo0zPI0wct5ekKfPiZEtBz0WyhtRLcLWkDkez77BC8CLwsXUF+71O7/v3j4aXe4lqIUazl1QbpinpeA2lRv9MCZMEqZwz1SS47bGVyKkz2hV7uk2vf4EBNIZ9HTf4TdqkzkI7RaV+1s2JrO0hoW2zS0OXPf5q02tYk0ARE7FJMu6AEE0ugfza6ius2G9pTNJbRQKmrhvaNPbe1HUYTUnwCz4DlgbvoQGh9m0z4YSg3avHgI4ZiC+YiRONNbQ==,iv:k48lbWqf3syMbI0ntgY3VR77pwAcUtjlznMUixorbEg=,tag:1TL3WIXLkozpMBEN1sSxCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8VSgXhrVkMCcI/3jpv5Vc9xOEx1swn3L0bcUafI/ps+wN1pNldml7g11eECYdWAh6nuysnaXCfwSfeKhnyTz1dU7l3UYZehFNM1xNdChXQE4gc12g4u5WBbyTNbEG/1oKvJ3cwLaw6+T+YR3g/b6or3PoQ9j6ZiNlCJ1zM0JZ52UCxXBJQQtII/l4+p8tlQnQEBgb2VcRrwemHs+kPtL7XltK3yI5OCEQJ8v,iv:KaqFEbhXMYiO7DiFXIF406SsbuCyTLEHbzsfovcxHOU=,tag:OdcFRrYdp4vTnZ44fSHCqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOXErbkJnM25yWEpUNzNF
            ejI4eXNkd2oyZVZuSHhmMUNyU1NIMkhkQ1FjCmw3ay9kUk1WM3JiL1c4L0gvY2Jt
            Y2ZQOXhydnpURHZDeTVHdElFaUdyL3cKLS0tIHVkQlRNK095NFVMUHF3Z2U3Tllo
            cGtrb0VuMEM4cENMaG5kVTV4Z1NDakUKJzNpFfg8KzagILyWcbhjKu6B0e+fWQGc
            tKV+WgtYCgJ/YxWeLxCZlH5I8NNZMqKOLzexrKDSSrEpWSmqoL4qpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T05:22:19Z"
    mac: ENC[AES256_GCM,data:tWdk4QjxZdB/hIygk92y1ANsgHkldvRjUGVZfMditJe5WsVwCptM3paJXOWz9aEtOdGQ5zPzVYfATrJRv6qA11H0VZ7zRtTyJovwjzRo2AsVHVoX9v4StjC2z4wH3HLIiuSJEvOvRnkMI3yfHuFPdDDRHKF6sXn9j1YgxQl+xkQ=,iv:eQwjw93kP5YSe0iWbla07Zw9YNdk85jEwGwhJvx6i0Q=,tag:Kslqgpev3WtaUc4SqqEPZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
