apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:g/uqxEdx6oiaq0Dw+yHxvMJsF9wza6iGnhazI25ut1DKqkt9V5lEzT38JIGkHs8SjAbJYtOz/R1PhsBaGcgMEpERqrCGHhIfGdq4W5IqC5Y3C4yO7Rb0mJ12YU0rxswK1TUsZ2OWHdo65iT5Xgi9Pf3/OQj5sPNy8+oDAFOZEXTv5ZLohvBC3j4RsDux2WwisC8hpTdobhCeqpYl0NIIHEO5N+49TczFvybKMpdt/5e40Z/7Wc4JabzbQSDajsc/u/zrds8UJudNHwmyFJcvToPd6ugSYenNcraXhJdRLF0m+cxtU3ZkTHMJnQHEHcDJ8CKUdjCpx5l0zXffp+TAOMyYJcxfvm3pEE2b+QNdtE+9QTsJLM/b1Jw8MTVFYZ8Z,iv:SmI9qBGP7C3cBZkjGJ7yxi9LrfeG6hsprI4GvqqNVqo=,tag:jjlAnkwAdLs+uOeBxBI8Bw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1GThdcnace9mY1J1gEQOZikWb1+APQFkI6ImYGBtw+LhfvhJOhWrDpA/95OM1jlPGyJJAU11g7vBVeX4lX8UgzV7Lmbwg7wUVVIYa28+0K8AFVWq4Nj6eMY9Cp3Y8DxL62mLtGp5T8mS//CdQXjtvz5dpkM/Wyi2DUrDgRwxaWVqkAPjA+O3uJ3TgFUBn0Vz33lJ7ijIIIwMqGntuU/f/WAFY3yPZSsAYVZbyc/OOklsGWr0khL/cDrRHK+aYv6R2xfHH8NpWuEVRn1eLw==,iv:y6iA2V3LpYXxiKO10IHeTeHE7Zl+iSZ98AzLK11ZvZA=,tag:V+B+RFsqIJmm1ZTEDWK2lA==,type:str]
    known_hosts: ENC[AES256_GCM,data:r2q3KDBKEhKM0fMmp1vcjPEiAalVRkOaWdT4/fz/bApgLI8MjkhuFcErR3l+O2kEzlE84n0zTkPlKc/iaQRIFVxixzK4Kpl+Tcg4VWlWIVb44prUN+jdOnFWT5itpRbLWNEmVtCHtvVYy3AYN7CHwlR0NgIAz8+j8KzOB4bAA8BndlFbVGNprDZYFtTaU7u7M5mMt0UrUjnBVGfS8xteD5qxSukfi+pCfC5U,iv:FHaCu8MpFt5zJejj3br2v2SEWVMR3bjSln0poAQimqw=,tag:aerjD732P2Lx2AkdhIToGg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVHhJdmtRSW12Q0hMajly
            UFhSR21CY2RnWVZKYUhPWDQzc2tUZDdVcVJrCjMrSjcxRjYyVENzd25RcEJyOGJu
            STVwbXZqNzg1YnNDVEpqVkJvNzdRQVkKLS0tIGVXdGx1eFNpK2E0ck5mVXRaL0o3
            UkVyZXlzZThkYUE0bkNHbGQ1R3g5a3cKkTVUia7TiQ/cry1KAhFgr9b1TtJwV0FR
            NiLjzraCJWqaIO5yu8a6D19gILqdsAVDSkPic9beehJaWcrxYIrqNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T06:33:24Z"
    mac: ENC[AES256_GCM,data:y6Ay2KT22MLk4kgnVptqjLAAsMWgaT3sgaAxEsrigefbOMEEoqHEgHKj+LbOq1WuG7qh8FoO8KMrlWOpvjF/mvxOuQ4TxEDGTGTgEw1Np5eVpl6VbBsz91+qNP3h+62PGwyjw73APqGBZ0lO6XaUcXyKTzdxI9tvsIEwghhJwB8=,iv:phmu7vRRqVeik8bHN0jv9KbwKwuGADOoY8/24xu2j6U=,tag:35fEXbAPGmRs6hNTrYD/+g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
