apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WJiNp5pExcKpJGMIcTxKXHhJolH5rIdTWAPZqZFnk4JdmSm3+Tn6g6UEDW9XBW7AUYEz4HhOiOEK/cmnDkk70PDIco2Iygh1FWeD5/PvuDQP8ldvXlSEv0ExE/W7XsJ9KP9y6rjdKhaMeclI+Wqhr5ivGmDmDT0lscNmy2qmPeEBJQssytLymGKKo1ExBPVUa/lQeo/Ak/BDoy7pm+KMcRUHg3y3ELLTj4igj1IeGTuuPIkfsRJmuLQeGlOsfLrbyMM+SbXpHJD9iXlvq2XR116KnP6PNMIvuekNHH5VM2JazVqRlU+1c9ceaJ71yC1fR3Oz1gd7f8KYlqe4lPq6A5wj10h06PhMANjLBf4V4gX2dzSw8iSDmEr+70z+Kg9/,iv:R5TLmbdRUbdjejNbRx3IzJKSMX39oSZUXnG2c1VJjO4=,tag:8MaBFh2GKgiaRqHOktaH3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:rHHUyGXQn7P3hThJPL3XbgIq3zsDV1d0w70e8Lg/M+/mNwrn8HzxKC2jAzAOyGRDoSrb5zt2fSdAIL7RyoTCNX1em7BORg+mOgyQTkVlLbnv262+i3W8G92hj1kfkdS7XWcj8Hp8TMSedFzZCrNk2Fzp6XhLP/ST/WAq9zRCJq3Xoq/GeNITj2qJRao8by0ajb/sxSEGSe7vJpn21XLurpc+MbJTGYVOwBClMCZKhw1fOJnPcrs/2aMmwCcdbK2AMymQr97mZci49lIpzw==,iv:U5hnHBe5LoZooM6oFKVFqHzAG1DROFFlp7u1lYBJ6n4=,tag:/WhrqFlrULRKzMUYf82etw==,type:str]
    known_hosts: ENC[AES256_GCM,data:xmswnlIRP9nagkNCI7bJw57CriW9lBOZ8tJ0SLicbTnujNlPNf0DMZGxW7iPuTbTPZO+sXqTAp4dQgCaWKo2cXymHgsosM8ORpvq4W6hd5CYE2KA+oSjNATu7Tnz22D1H9cMBHJLLC4DHQM5ubfn5uhumc6qf4tFazxCGTFJFWUbQlK935iiaYr3WnhVO3v7orjS+YgmqjlYVrzaD6YbZ3zi7y1zlHaZ+usa,iv:6xaMof3NoONqjyQM/6F/4sk3ha4uAxz6tzAzGhuvCT8=,tag:u06hbsZ/+Zmd+FfH25KmMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleFlBdFV3ZENubmNyM3RQ
            YjZQc2dnckRSRi9IcHg2OGdxcFBaKzQ3L1NNCjVRenpPelVlb21yZVFQUlhKN0JZ
            bkJMdlJNS1REaWwyTzBTSVV1blFIQ1kKLS0tIHVTdUZiL3A3TzJ2YkV1cnlOanBx
            aFFEaDV3TXFxOG13Y2FzMTRoSE9wQkEKbcWdH+uhuFZJrEqtpo3X1Wg0VFc/uMhm
            IzoxXVnMZjWMChswRDAc2lWQuvqTrkN+70Km9Uh9rIe0dO6SOHbsqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T05:37:45Z"
    mac: ENC[AES256_GCM,data:k4BKTPOdPXxUd9ssfED/98pp/44XF6kYgcaNv46WlvJn1dGYOGrY7lIKYG52hpI2vfvtEUvOT1iQSBQ/cnCJjEizRAnUwQMjb5JWV18qzNH42DuxIM1mfXVcAJXAZ8OW6U4mKlENiPpoGlVAwB6Z6lgI+RgzsUPLcNSv6e905QY=,iv:XcxLDCkFQPZ2xkqBq/SHvVnfJ8C3lwYqPbaJBjqL/iQ=,tag:pWQO3Am/TpHEbSZXdPFxqg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
