apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lfL0oTykmSO9VkpkxVbHvdu1cErYTjzlsuSZvNMUxqOu7sKtQGMylJU9ITxny43F9hRToex8mc7LEoS244CKOjkKxtsE+eJ4quh+TJjqe3Li/Sn9+Qbk1vIFo9rDL2yCl0Te9WsoOsycYkDzC1tMbcVh1Ov2ev0FJpJJYRYHj/WNv6xWDKTOXRSNmDPVZmlp5+R68lQjMIJ2VhRWNGFACeQ0g2dqS4FmVhrwaLQs0+SnSc71iirP4FlTIs9IeceiS9dks8unaFMpCrAKycXfOXamVAqCgN7JZbhyyoa3xw7JtCBNK/D9HIhUe4iRYBAan52VWgq+0l8uEgaveKPRX5yvEuKb2h2MdAEMuZl8BtdMtsycs3zCznU/iqxB/8Ng,iv:bLTcoTLr3D2fP3dzTKcuWNfj7p+5qFDnMylYIqdGQPI=,tag:0YvtjPdcETsZemGbd04UtQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:BdidtB/1gCb+luD04I42OcFZRGHcVv8VRNaRKO6vc1l1DUABX6ky0KNHUxajcmQMKaXJdTMOe70325qghxBHmUqqPSq4fnhRQ9QUBCSUoc4tFnXo6PCgtRJwMJkBTspnS+VzMsEbwAtyc7ZAGj3Sfmr4s+d06Pd3BCK1Gt3NND5mIuICNNVsu+IU5/cQYTR2FEQB1QDhnf/B5RljojMi9Zf1lKlR0nGHgKFVlyiQg+HydcSliBu+6C39JAenEbsLKjfzL3MxRfrXyTY9WQ==,iv:QTNY3N43gY4lS600htbBjoqrxf6a23MbgX8LdlsFKPs=,tag:58bcsSULvX6Hz7a2z2VhLg==,type:str]
    known_hosts: ENC[AES256_GCM,data:DDQuWcwSkVlTwcU40QKux09lob/4P11ObcdCSlHyqoAOQvEim6pzR3KKnBcZb0VUdpeyuR+z1k4oOqVmmRtcQYONdOosDrZVOKB9jeZT03mA2f3nLMWEeMZnOi5OucBAsfrEEHlG+9piJjvOdaKbsGj+IueprFRiuPUOoeUeWsER5OAeJydZO7LdzD2mGYBarWFAS8UOsieTMO8TUhtJxEtwWyF2YKHArbl3,iv:kj3FU1am71UE0Xl6PyI3baHFqzU6ZtQtKRx9xmh1zZ4=,tag:OCIqhtf+b4NtVqW8+/MRpg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUHZLUy9lYjQ3V1ErbUZv
            ak1ZckFrNi9rcWl5ZC9NUVN0T3FtZUNVbnlvCldEUzA1ZHFSblB2RStvU0J4VEE4
            Rk9jU3NWVEl4OElzNFl5RnZVc29NQUEKLS0tIEg3WnhMdUxDajVTYVl1MDErc0ZX
            NHRxQVo3eWZoeUhPTFB5ZlBwbGpiWncKyeQRjZIMYTBAmC0Z5lsvKGPwXq/ou9Ch
            9JaXDSJ3U5cSKGnimKHESOrHA2tVjMpC2qEtgTqkGV2Of1r821FacQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T08:10:54Z"
    mac: ENC[AES256_GCM,data:+cUHh+QJynikPgvpgO0qUZtaW56Ob2EgVEXB2jg0U70wMNt0nz1b8WRPirGqrbGY47/6NxlZ2bcc+P1AqffN+G0byz7KXxY16kZQfSNuyDYatmJiqjLhoQwpKMOhrdfrPR+4d/Sgd4DjtnFEzmv+UoehDXuK/rGC3VTmCWXX1qk=,iv:2LEahyCAW/sHdIBrfQsnVzNwwXEAkZxDz0N8AI/WuKE=,tag:q2CiJYWUa1uJv85B7/81jg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
