apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xX3vsHPgRio52yBGJu7eUQXuYvzZNhCR8NujgAhcmL3HAN0KZYfArFKewNrWnoYJfADwQewDwVnXZKhfuLjbEERu0ILd+ALYEebw8CK+Otx4K95vOCzsbuBp228wJq4p5WSxHbt1Nne21PvBvUko06+5CovpyPX91X4pbd5WRkGsu/jPNIyNrhmXwE983GOYHcbimp46PR27c5O7qmEbXmNlLzj/C7DBNvF40jHeoXYXEHrDjwzzZE6Dh2pzTDSZZjBoO7VPReS137coESymizj184MrCu3Ka//RtiwoW3e6R5bvjgkR/bKiE+fdfQK6risjkzaiv0d+pAnayBsurjnbd1YHAn6+gG+756KuV6EkauhzfRVp37BCjSASXirg,iv:y7uOPLEScVTxA+YUpqcl+igoXzGW+gK9KLfCfA3o7Oo=,tag:N5IKfqZZIlozhugYMTegxQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JtQgDT2w1h2ZpOTRvNRSy5VoS67I/LHHtsNodwm/IeFpv/7T9nlO9pqmD73yJTp1EgkVdDuqXQzxZxSNdKSt7fAPap+83GKeVIBw3Ur2WhPy9APYVhMevdTHf5FncIWqJ8sOMMpv7RG31HIgD/s3fxDX7AJmg31eM22HemihrSRS/AypTMc+VfsSgxEvLEpniNwiD8pUITr4YFJ00ijhgV3vPqLoV0n8xD3RE2jvP7DiljrWIVkLPgqum0M67abvMN/d+/QcIdTj/XRVGA==,iv:/ckqFBKuLCta/GPmahTYwlmGeHqrXUrgSVCAye9tXgA=,tag:2oVaz2v+nTQuSci1yk6HCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:aqF6wtw3fbkaTAtmhJ5P9mcZwGRTeUv/gaUOATRAAeUVis4mTXSn+2oOVjY5BwGOF+oi69RtnwdVFAcEmF2CNbScrDDRRZlAhL5TvnXcRj9C0dCRIR+iqXxrfsItXOOhyt3dbpn4BIiHiJ5+AMr6ECxVMCRCKIRWf63NPywRaV96DqvauQLDjGjLfnIvpBAOK9B2E+QFSVKZcJ4d4gX91fDZs26TSuZyYCQR,iv:B7soM6QDpbjrsCW9lB5GDKTjWoUAt0JTGpp2frkopDw=,tag:vMnZqRifYBwgPdAYW1n9WA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheWdUWjVQbURMTHlDZXVp
            WTlLYVFQLzE0elY2dXBvTUJDSnc0YjFjNHlFCmZ4WEVnd0VDaGFxU1NkWnhNWGxW
            SjhCRnB2d2dPOCs1ZTVZVzN6YkxyQVEKLS0tIGM3WW12OG9GeEpNQTNaaGlleXZz
            Y21kMFlTZGVYNWk3WWY5dFpEamIzNVEK85gxa8PPmUHsHwG/gP/WfWBh7P4/gwvG
            vaFtL4YrfEfIeWI0xTMb6x1Bz8vW9rbaASix6BsjOtbsnbL21y1BIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T06:36:58Z"
    mac: ENC[AES256_GCM,data:XzyCiP/12Ecb6t4Cp/bfyx7l1iheyMd2JmoCLPHH7cTtBV0xRSaRwJ2k4QFa3mROpUBgiOiBm4kfktrtOgttY3AddiQTsl5UFpoiQxABPloh4KwztZExAHqD/uNXMilvIC1hYI4sUDKGK0eLw0/CYYj7HSKKAXtQsUVhdOsCjyc=,iv:YCyGYc/eOgKf8cuWT2qi555YGrWkR7uGcW7hvQuMuKI=,tag:OGGoObciTsh7OZUIYDo+GA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
