apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iL05st4/iuvFZiC3DbUmon9PvPmlvjmPFqdQzyTE8hQbRr13QWvnbbXkVcSewNzyGcxBq5SM0bsgbw9sOUtYlLTBmYS/l/ghwf3rVZXX7ho4y5yeNDxSRm0E5FoytTwvGbD/BIkAzYTogNneir2JxABrCb0EuUkofBHUQiYwyIXWZMOHH4kNgL/WmmRqb3PZK80CXTBfv3ZhqBP4rx3bzJZZebsFZPsqAgNWbeXElC8jTIQ9Pz4zr5pOPSzVjyCqEy4ExJSj1L4E9pTmp0UM9AQb0yK7YLyjF3g0S3etlQCsmqzgdaK5ihVwOVBCjSgaPF7+xkTgwPQzoBPkV3NLy+zV8jWMLCeT69dRqy0XY+LsSh+oMIC9gWLos6HoOEQh,iv:Bps42ECURFieVsoRaYguL9zY0LXgcJzkeA6wfuSSHwc=,tag:0ASfW1QwFhgqCEs1ZCfj0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:bWIlKG/1iUyeO53uUBz7l/iKoV02vIftbz5H67tUkOfEwaDX+UsCgm80/0TnfKCb6RHdarFypDoNJBslk7Vhpf+cJ0nMX9/rLv8gJ8ZxIwWvNjJH01MVd2tTFZy78y3OX37vnCEmn87pk0ea2MfJk3fbmT/4jQZSQfIDwtRcF3ZWCyfRDa5p3dos2Heh4MaB+MGikN5h3LrESLsxxLGSTOVutTrXT2dP7AtCh3k2KwlhlEplH6Lr5Igt12E/t3TzHd/2/iueHZS6zvCXbg==,iv:RUcWp9/x4DNUWbEtWkBdpxemGZN7oTaiemT9nmWi8s0=,tag:f2+4pRHEnBKzXTpe8zMEXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z3+XUguSOJADJk+xO8hYiElcpR2xAjLmcjGBdgjBnXUD6uXgJ7wCEzqwyap9ACp7tOflkKcseZ2A3VQ+MHtlbVytIwtHOCOJbzTEchP+U5XlJ+XHeNoBy3SBGgrfX5gJ8nsYkm4UpdZnBpR5fExQHzDSsHKv/EVHqQfRb4bMPZtkXjdo5csAghrch8D6as47IAkHEscb6p5v4UfvLaE8uJx7dGbVmVYsjsz2,iv:+p1y/lvB4EhNpztiSFqYWaiUYYdeYXLRkpPDbRuqI9Y=,tag:rBkarwNBXMEbA0eFwrbUrA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOVdiNUFNQ3p0cldZWUVj
            bkFkNitBb3RqcElKeFBLZVA2bjcrdGtiS0NFCmh1RXlWeVUvZDdGblhCdFVJQUpC
            WWwySVdFMUpUOVFYMjdTOTRKZWRtSk0KLS0tIFNGMDVOVzlXZ2xVN1AwbU8wakZy
            NDk1R25kSFNTQjRJM1FCU2tPYlJYU2MK3KqQjmlgkfwPohKMw6KqlDoO20IUdQnH
            VLRiW7FCAE+md6vyW0aL6NiS5pAb7komhdsCNYQU9jy2jHXFcsLTDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T19:15:07Z"
    mac: ENC[AES256_GCM,data:ANkHYQ10tXEqYnGVCyC9rAJBmroJi3LYo427QD2v5Weavi3jeRBuf7FVZ8woNdDIbJPwem1z8+SmRNgMhqLAtNcp3lDyztzwXDPBOue5PuIlS8eKLQHpE3bAXQsKSpj/x8pgm+74eT1Z5B6rqfKv/MLTkmPEkCtTVCrvAPEoSz8=,iv:gWNdq5w57Jz7up6EIeRVMFzzgr+JI37ETTGQ1mu6Kb4=,tag:ceulQ6Fw+wJCpx9gMhZZQA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
