apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KKUOmmVlprpor7giwdOIb7yvnNWR2zrNejmyMEdzrv3A+1J2i91OT4pbNh2bAHLg2WgKq4ZhyHEfa6uI4sHW77veiigE8wRva2rqoa6hAF34MIBHb05JZRVgK11td4xLNkLmfFqHZZH+rRLPDRV4vfD54QlgefIO2fJ3zAB2VZ6U8ub1o0043pW3bmsp8YrlMbGzUYOSqMZRmcgKX49fQjAzD4EW6XfGf0/WeOLiBk088DXEFW9LNLwzi6/K+WdXgkljJLmSCpy2tA1S0KbL/P6evwABwOs12Wv68H2jA3s6ViwJE1/dOpx0J3H8iK+JQN3y96hIcW0UsNkPluBt87VNM2BaSFF6PrYQS0HrCzS/EtsFnCnX/o485J7a20Am,iv:gZcKmKT42LWNscoJ/VWrbuGsgGjKBnpdTV2k8z+Q0kg=,tag:ATczcNYPpqBdYhjmvgBdpw==,type:str]
    identity.pub: ENC[AES256_GCM,data:5+mp17kRw8kASvMNak2RXd6ilAuSY2Wnbmb0Cb4j3LV5Cv+KjT9qEN2WZWsKKS9bW/9O+QTHU8mOPqOvTmlVPQLCkroY8VU1Ofh3PT0GoqwaRAG0fV+DnG12ogTfBTZD++OJSzM2DGB4c6uwCNABBmoUI5/IiDTugmhdhyhUTBXckX8cj8aTQi1ZQX4/3hnIBR1+i1/SiPg6JvtdUxSyH3IlUNqiWJuY5nIuTB0mkNPBtmGwl/QiTdlE/9XJSyuDfeKRfYUliAt3bC12Gw==,iv:cHEv8GDwQzYTjWQYf8Q8IAP8lKN7MrSg9Y6a2PSHJ/A=,tag:7ghK7dmGgmwhjauoRvM/sQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VN6KDhh5cBFZp88Gz/nuRSSgIiG81NNkf5rM9SQwVsC5+DrQwTm5NtR0B9arZP+QqMLTFo6+QD/n+gJgH7nUV06LPmYXlQ+Fl/PyY3TaRxIYWK6MROeHhvIeW/t4qK94LemCmTemzdTzeCupznP54vdwhdAqQxclujBorZahi8vwlJh458TDaTcTjDlnXvL3qoiInSzuzIizdR7bDHK6MDWOiEgDBlHCLZn8,iv:cCABFOUEBhZJCarU7y9oTBtRzT+1M069Cg+Bu7w0Lmw=,tag:5ORPTX6ezyxHNQGedta2lA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMk1WMkZSeGxxVzR5SU1F
            eFc1ZHZoUmZDUi8rMnZySUllUzRIenVHelhvClExVi9ZejRJSWJaZE5ZaDNJdk9L
            WjNSSGlITEtnRVZGMTRUMFZYeXozWVEKLS0tIEhMaW43VE9FMUt3QmtCU0g1Smdv
            NTY1eXB4RG44RWI5dm9MODhmVkYvSXMK6ceKN+YUjOqo2DS2PIpdAXuK8QAHnf+4
            kjTzWksUmgj7L/9yR+yGXL/Fd9FM26bVH3yTwCPme8yxAec0T7jgAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T01:20:27Z"
    mac: ENC[AES256_GCM,data:xgDXuiVjwr/a9NhdDonUyc3vSakXki/PkMCgfxqXWbFbUPdq0IBDocxUQkqa6+MQruSgWetUL09J8Q26FNWTHU8I1+a/+v3JKNg9lVVcOvu9avtP/kJsMAUZ+hKMZH+YevS0r83+ydysBGmKPMYIUHNdAsH9rZP5JjrsFdwY0gg=,iv:xSEV40XHaxbHYz6iD+ERb5A8lChV6xCrn0F4an1+mfA=,tag:Rwh4H55tuzvyq8eocLkAdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
