apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m/9NQX6CcS1LpPiL1oyRwkQOb6U/SGQPEgYI8FasN2X1q8z2GmkmrCJZPcR97HziC8ZcItoBeoI7Aswah8Krb6MngYHICyYLEXfaNbXyO5ybMIqqg0qZnMGxiYxsJAR8rGRCiQIIXey8owDUwlfFeGeKhDhwqKhH8QPWVt2HeIfLBcgUFGFsIFmZ83urscjAWgqciBYsqLkY3wVbvSWcH45GjJWS17w90l/cG4rcOJkBghlfOXSKglY/6TywMgK/f6Wa6JsYZxL5zml0/7LnT/VQU9aQj86dqJBPhdr+FKMv5zEPx9fMUUxFf/KMduJ9lajIHby61wbyuSTq9bNd8uikIrcgPuWg0VpitnJx/+ywJ4847h2HDwmz8w3kb6gq,iv:yizKNQTPxZcFggw2Rq6C/dmk5oAinbo93mY7/lCoJpw=,tag:cj+I1VCyNbp5Ng83FKlSQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:IRIEvY4uFFXlGhk7pTM72i6EO9XIVvurJW/1hHjzIr2CKHMHXri+SThlIexxP8cjAjcYsocmlMUj9hpZR6JtzadvmMUdmHjDollr9LpLB9/bGDN3arx3g3XiAwkrtMAeV8NVmXiXK5Rqot4ON2J3spMllHdX/DwLPk25ZT4aI0MS66EZLRdRCySfz/6C6oYc/GSk+R7qyeeca8kdz6kn1a5Ila2xdf1JLwbr8bMwwfboepGsFhsNF7qfT4ijrJNVNocYeUgSgtSAwKpoHQ==,iv:Xyv7C1pRXEOR461oDX/zb3++Tm/gCkdUMHAd+UFyGtg=,tag:8tiICRdpg8qj0FjtgRf05w==,type:str]
    known_hosts: ENC[AES256_GCM,data:WdvPeezwKIJNkVH+ymPH2/4eDCPTWRz0139s0awm+wkV58Pqd26cQUG0Z58TvrQW08PetCaS5oTg0prjg3ojDWQQTVx4U1gKkVum/ETdJ4ZspO24yuJuiLgWcYpnrcM9EILZ7Si/PUkTzmlLMOrB5GIV2q6sctbRCwvmOByrzkBMRFEVNZJZ2IsRoLFN0hHrDW7qxps4RNKUOG/5PPcFWQnVC0EbO9CeK20R,iv:GlxKTuD2g9MXKSZaP64FzmwXNpQvi7V26bYjD8veGKo=,tag:qLc0St5YzN4jJPLKnJ63Pw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybTFQd3d1UmZSV0g1YW9U
            R21JTzZ1eHJGODY1MGtpUXd4Q2M1LzFYamcwClhUWENBUm92cUFUd05mSHNvMktJ
            SE5PNXVnSGQ3cXB2Z202UVVVazMvbkEKLS0tIER1UWZqaHRLWlc5RkdoL0hKa1lY
            Y0FSUlJJRkVEMk5wSnhjRWJtWnorUDgKTMgC26YW5WeWuxduvKiY7Dl7ok1RXSX7
            7tq72HURWCrL6fCZ1vD3u+ziLfpTZLm1c0ahYWFR5Kk3HNcxufODng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T06:54:25Z"
    mac: ENC[AES256_GCM,data:YB+IoN7zx7PToq5jXvkNOTtjPz5VJ5PGRvCtPkOW8xZmdlRMxgCapu2yEvuKx8v6Vh7wlnjR9qGkvXAXEcpG6KfE19m6lmcEl8ESAL8HY6nBRUbjTZrzAVh8kTthhi50T3fa3rTFS+Yqwif+wR3lJna43agW3OorRpJFT9DtyAk=,iv:VFsuGvxuMnX8he+y0PejmKWHyhb00LyzaTLGdvDP+Uc=,tag:I6aj1YCXUjFLPKN9b+crEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
