apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KX2AyDssW/GT9MJzEIOsqVDVY9eMmTddUsa5hCZY7ThSIFkydyc+iYP2BULW0H0wu/LECiw+hzFE+DbnujotBMjwDKgnUheGlx3mZcAvIWyEf0pFG8fBED7FTZ/mQXIlCLp+TNQdAJtrYF7GwwjyxQJALX/hawG/AlOsDWnW65/+chcrfj9x98jUFgru+uwDAWuhJ0TJQxQo++Ss6nyJILd2EkIaelJWynaLgTjhkpueZV9KMOuW4gmL8MNhTIZG8K8lMMMiOtoMhCdPtMvLgStbqh0QDYLsGIt3UqLwxv133ihS9OxKesQSZHluCwg1w5Jme9lY+FOuj0dDS+kSEe6W23smP6ucvqllDK+l+rXU06aUGrQdYeF6iEUCb37L,iv:OKXCGjrwCHPKrk3FXB5rf+PNnEpUEUREg9ejMel6hPQ=,tag:/9TdMZ3/CIaGj1nOcB8I4Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:gKFxFcFDs8h3T0EIgIfsw8f3sRg9RauWrk+Pi2o6D8wdF1TmbYFhzrQUjJLobdzf/irF3vpmG8PsrBSpADpxtQDrhFNbSQ8OSokX/tnnqD+/RFtNSk3n5WUk4dEgLG+vaP/JB5Khk243JEZvRfJdiRt+iFu0XTay0jIz4EUGMl3hYxAun8kjqArO8fiMgEeuUNg+QcPjFjTNxFFCXH0QAx4LL9cFRm4zHYf8AQF28SIuKe9D4wz3l1vmmc1E7ouau7sC8/zdR8aKiZ4tuw==,iv:LAUsrSUjnspTJ/sjhUCwyYcMXTuURhgjVG1On0SoMdQ=,tag:rkcXgjnm2El0Ng9QsAHpMw==,type:str]
    known_hosts: ENC[AES256_GCM,data:acxHwDOvzpA+jrpcW86MifG5oClFzLlWVS3SR2OMeJagfmXb7Zk3NKq3t/Riw0a6BMuvYMtvbDzgfUQS9Hm8UKR0p8n+2FtkvtiWoSqtXY1lM8dM82YkN3OYxaRMFQ38/xFbSzH4STcYSFE2UwhXDNTPIGNixC16US2VkfKvIjW+U8WabPCNasGDCxTmW6t4gRLFf8LgJdRZAZrcox+0DFNIzo1hnbHYbJc/,iv:GmuVtbm7MeuKuZrMvcOgRdj0wkflq5EbupIyRsNiDew=,tag:z3gs99MwZyEWCcbNJm1ICA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESSt3NXB2MkFHVE9teWhj
            ZXB1RC9ObGVuU3AzV2V6RURRSzZ4ZE9JR0VJCm1US2xXSklDeWFlWXRXYWlpQjMw
            aTRNajY1U3pTRGNOZ0JMWVZaZlBqWDAKLS0tIFZzWGJWWWFNVVFuVkJuNFgrcThs
            NHRjTFJtZXFXWDRnc3FqU3dRbTFjQ0EKZ+/zwF0S7MolWldludOy/Jk0OpJL/jYI
            esgTMhwmGkKzoJWLNjHYO9Gfpf77WFv5dPGvWqaBF1H1roIAGqjuqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T06:22:01Z"
    mac: ENC[AES256_GCM,data:123Gl5FymIIDxI5wMD2kItUc1I3FHC2xk/5Wnfsr6Bk/DBxRcOiIYUoHM26wMtoJQTOTKqYqU8N0LbuimhZFC1MSyBjG8Tgq67vRlQYcmsObmGkKsVLW+7hXDso9MwBxanINkrbSVUdMjofpdpxgbmZKCRESOrxsuBAxqc4chzU=,iv:7ZtL9ZBga8ZKBFq6oKj5A+a4MN6suAJevqCfjt7LP38=,tag:xlpRGW7zsWcR/wwgdmoRHw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
