apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nyuZcIZ8Yo9vNR8pFjiRcmaPTltbg3Njm6Pk9amiD8VqTkC0sY8cEFx1FNR7sorENrnEIRkX+ZmmYu/U0A6g4HKVjAM0GZhvByv+ZStg41We0zJ7RuLLo96QVpM6boIxONIrU4Ti1ICztMowc/R+i6c3BBl07SNIX69XE4negpKSfKABXmBRVEDzRF3ZAZYw67cWuPcHhLgkF5xSxjl9XpnjNYtMrGaImPS19mZ1a2tWubmgnXzm0IGywHpblpClL7Rg1AIU/fbmoVZchAw0CoIXPhS5eh9rxgNJ5WvW/Raflnls2YS28znK7mOMmrtrwEHmEAT2uhYYxCp/FnP7BsPdoCG9jwVzju4RRdAh7eh4Qv5zu+baprys3E1m+uJ1,iv:Z8Zb33v+yJIArNocvyCyxdww/gyVWf/zUQFNhvVNNRY=,tag:QGHf/O/Hg/AcaFImIERZeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:yYuJDlz01XlDt3qw6rM5xZIalLBHiY7hlm0xAmjoq/wOMtP/RjRklYnaee4RbDHU6w7SRjIRfIIvQ0mX7n0PjWrfKMEYRMYv0XKzWZIpboDDp2Va3j1kQ47shgXvB8TaOlwJvERPaOlcfPQqC9T8IFzpBblPlLRUmF0Dg6dngAKdvcYkbsU86024YYQq+EkddvFrprZwJPsyBQWMS7h7FJ5qWjEhjSb1cSaVMfTtXG/ZXeASCmSiI+GvjYi8sA8G0s0wFHiJwq1uOI6N9Q==,iv:43oj7QtaMV5LUYJSvQ+aty5NXTsPr77BIM8+IsnRK0U=,tag:bhbJzwBb9BuT2hnBXapGsA==,type:str]
    known_hosts: ENC[AES256_GCM,data:UxO+wNJVdoRkp+RDmz7ijNrcazFjgWxY4kwxFIpaH2BBnOhx7PczcgPU3ztrbyJLApeuw8epac8So7jRd1cJEknNCvFNaTuu69mtZEjnrf0j6nyG28IZXB9w7mr8LR+YP8oGYsYZJOFbPEZFUEzDzjjk6CbLxxjMIbn8oiCqpqlfulJnNryZTZqTe2EG8caw5PmF3o3uO0YVQdD0/vs0l5Nndrl1CE5/cf8f,iv:9LPW1YdYgW6/uRigKEcqBKKp6NHvGkIY9xxZ9P5ckus=,tag:cqzandIwS9XY9wOnINpKTA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1va4u4r4ma3xu2zl3q6j0f2ux0u6p23p7l6uluqzuv7t85zsakukq2vt54v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cjJqbklFVzdKUldxNE1M
            a2R5UWlwUkpkUUVCY3RLYlhWK1k3NGxrbkJrCksvNmhMVjVwNTYzNkx4b1dxak1G
            VUpxWExEcmo1ZDlsOXFIcDFnVG80VE0KLS0tIGFvZFhINnlKcXVEUHpjd3ovL20r
            dXl2WE1zdkQ0d2hSemN3cTZLVWNnc2sKWx9ng3/CRvM+8VHGO1PYvdCNW78HcgmN
            fy0wOnjPYShFnZKNm11pvLQ/B2H1AVhKf7MIHslAmXmI2gBnDvQDzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T05:35:50Z"
    mac: ENC[AES256_GCM,data:+AwDZSLK3yBrM5SfleMyb6ZaG/3BgkaLPV4gxaosrliBrQ+I/5ZTbb5k0bkUWSOTXx4SccS+T3d+noOAqHyYKtoVbjCeQN+ZfiwgU2fPBoegaxXgtVmFT6ZI9jthMF+mXoqaOTgKSJTNAEngnNhSsA8amte2tA7vhUVUpddy9aQ=,iv:cKA1PBQ0PN/E4ehITRxGQHGRFxDnM3qkfl/D56QIAtE=,tag:V4H4o91kohAGTxAJht5iEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
