# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actualserver
    namespace: actualserver
spec:
    interval: 15m
    chart:
      spec:
        chart: actualserver
        version: 13.1.1
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: actualserver
    values:
        global:
          stopAll: false
        TZ: America/Los_Angeles
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            hosts:
              - host: actualserver.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              homepage:
                enabled: true
                group: "Documents & Files"
                icon: sh-actual-budget.png
                href: https://actualserver.${BASE_DOMAIN}
                widget:
                  enabled: false
              traefik:
                enabled: true
                middlewares:
                - name: auth
        persistence:
          data:
            volsync:
            - name: data
              type: restic
              credentials: s3
              dest:
                enabled: true                          
              src:
                enabled: true
          #server-files:
          #  enabled: true
          #  volsync:
          #  - name: server-files
          #    type: restic
          #    credentials: s3
          #    dest:
          #      enabled: true                          
          #    src:
          #      enabled: true
          #user-files:
          #  enabled: true
          #  volsync:
          #  - name: user-files
          #    type: restic
          #    credentials: s3
          #    dest:
          #      enabled: true                          
          #    src:
          #      enabled: true
