# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 15m
    chart:
      spec:
        chart: nextcloud
        version: 32.6.2
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    install:
      createNamespace: true
      crds: CreateReplace
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      crds: CreateReplace
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: nextcloud
    values:
        global:
          stopAll: false
        TZ: America/Los_Angeles
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
          s3_CNPG:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_CNPG_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            hosts:
              - host: nextcloud.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              homepage:
                enabled: true
                href: https://nextcloud.${BASE_DOMAIN}
                group: "Documents & Files"
                widget:
                  type: nextcloud
                  custom:      
                    url: http://nextcloud.nextcloud.svc.cluster.local:8080
                    username: ${HOMEPAGE_NEXTCLOUD_USER}
                    password: ${HOMEPAGE_NEXTCLOUD_PASSWORD} 
        nextcloud:
          clamav:
            enabled: false
          collabora:
            enabled: false
            username: ${COLLABORA_USER}
            password: ${COLLABORA_PASSWORD}
          credentials:
            initialAdminUser: ${NEXTCLOUD_USER}
            initialAdminPassword: ${NEXTCLOUD_PASSWORD}
          general:
            accessIP: ${TRAEFIK_IP}
            default_phone_region: US
        persistence:
          config:
            volsync:
              - name: config
                type: restic
                credentials: s3
                dest:
                  enabled: true                          
                src:
                  enabled: true
          html:
            volsync:
              - name: html
                type: restic
                credentials: s3
                dest:
                  enabled: true                          
                src:
                  enabled: true
          data:
            enabled: true
            path: "${NEXTCLOUD_USER_DATA_PATH}"
            mountPath: "/var/www/html/data"
            server: "${SCALE_SERVER_IP}"
            type: nfs
        cnpg:
          main:
            #password: ${NEXTCLOUD_CNPG_PWD}
            cluster:
              postgresql:
                max_slot_wal_keep_size: 10GB
                wal_compression: lz4
            mode: recovery
            backups:
              enabled: false
              revision: "3"
              credentials: s3_CNPG
              retentionPolicy: "3d"
            recovery:
              revision: "2"
              method: object_store
              credentials: s3_CNPG