# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/squat.ai~1tun
                value: 1
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.4.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Los_Angeles
    credentials:
      s3:
        type: s3
        url: "${S3_URL}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: torrent.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-star-cert
            enabled: true
          homepage:
            enabled: true
            group: "Documents & Files"
            href: https://torrent.${BASE_DOMAIN}
            widget:
              custom:
                url: http://qbittorrent.qbittorrent.svc.cluster.local:10095
                username: ${HOMEPAGE_QBITTORRENT_USER}
                password: ${HOMEPAGE_QBITTORRENT_PASSWORD}
          traefik:
            enabled: true
            middlewares:
            - name: auth
    addons:
      vpn:
        type: gluetun
        env:
          VPN_TYPE: "openvpn"
          OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
          OPENVPN_USER: "${OPENVPN_USER}"
          SERVER_COUNTRIES: "${SERVER_COUNTRIES}"
          UPDATER_PERIOD: "24h"
          VPN_SERVICE_PROVIDER: "expressvpn"
        excludedNetworks_IPv4:
          - "192.168.1.0/24"
        killSwitch: true
    service:
      torrent:
        enabled: true
        loadBalancerIP: ${QBITTORRENT_IP}                  
    persistence:
      downloads:
        enabled: true
        path: "${QBITTORRENT_DOWNLOAD_PATH}"
        mountPath: "/downloads"
        server: "${SCALE_SERVER_IP}"
        type: nfs
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
