apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mediainfo
    namespace: mediainfo
spec:
    interval: 5m
    chart:
        spec:
            chart: mediainfo
            version: 13.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    driftDetection:
      mode: warn
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
          stopAll: false
      TZ: America/Los_Angeles
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          hosts:
            - host: mediainfo.${BASE_DOMAIN}
          integrations:
            certManager:
              certificateIssuer: cloudflare-star-cert
              enabled: true
            traefik:
              enabled: false
      persistence:
        storage:
            enabled: true
            path: "${MEDIAINFO_PATH}"
            server: "${SCALE_SERVER_IP}"
            type: nfs