apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mediainfo
    namespace: mediainfo
spec:
    interval: 5m
    chart:
        spec:
            chart: mediainfo
            version: 11.11.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
          stopAll: false
      TZ: America/Los_Angeles
      ingress:
        main:
          enabled: true
          hosts:
            - host: mediainfo.${BASE_DOMAIN}
          integrations:
            certManager:
              certificateIssuer: cloudflare-star-cert
              enabled: true