# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 11.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  driftDetection:
      mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    forceConfigFromValues: true
    TZ: America/Los_Angeles
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: internal
          hosts:
            - host: codeserver.homepage.${BASE_DOMAIN}
          integrations:
            certManager:
              certificateIssuer: cloudflare-star-cert
              enabled: true
            traefik: 
              enabled: false
        service:
          ports:
            codeserver:
              port: 4599
          type: ClusterIP
    credentials:
      s3:
        type: s3
        url: "${S3_URL}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${BASE_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: homepage.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-star-cert
            enabled: true
          homepage:
            enabled: false
            group: Infrastructure
          traefik:
            enabled: false
    workload:
      main:
        podSpec:
          automountServiceAccountToken: true
          containers:
            main:
              env:
              # Set this to your host (example: home.mydomain.com)
                HOMEPAGE_ALLOWED_HOSTS: "homepage.${BASE_DOMAIN}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true

    configmap:
      config:
        data:
          bookmarks.yaml: |
            ---
            - Developer:
              - Github:
                - abbr: GH
                  href: https://github.com/
            - Sports:
              - Sportsnet:
                - abbr: SN
                  href: https://sportsnet.ca/
          services.yaml: |
            ---
          widgets.yaml: |
            ---
            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "Talos"
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
            - search:
                provider: brave
                focus: true
                showSearchSuggestions: true
                target: _blank
            - datetime:
                text_size: sm
                format:
                  dateStyle: short
                  timeStyle: short
                  hour12: true
            - unifi_console:
                url: https://unifi.unifi.svc.cluster.local:8443
                username: ${HOMEPAGE_UNIFI_USER}
                password: ${HOMEPAGE_UNIFI_PASSWORD}
          kubernetes.yaml: |
            mode: cluster
          settings.yaml: |
            ---
            headerStyle: clean
            cardBlur: md
            fiveColumns: true
            layout:
              Documents & Files:
                icon: mdi-file-document-multiple
              Media:
                icon: mdi-video-vintage
              Utilities:
                icon: mdi-cog
              Infrastructure:
                icon: mdi-devices
              Auth & Security:
                icon: mdi-shield-lock-open
              Developer:
                icon: mdi-code-braces
              Sports:
                icon: mdi-medal
