apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: hastebin
    namespace: hastebin
spec:
    interval: 5m
    chart:
        spec:
            chart: hastebin
            version: 8.3.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    driftDetection:
      mode: warn
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
          stopAll: false
      TZ: America/Los_Angeles
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          hosts:
            - host: hastebin.${BASE_DOMAIN}
          integrations:
            certManager:
              certificateIssuer: cloudflare-star-cert
              enabled: true
            traefik:
              enabled: false