# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openspeedtest
    namespace: openspeedtest
spec:
    interval: 15m
    chart:
      spec:
        chart: openspeedtest
        version: 10.4.0
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    install:
      createNamespace: true
      crds: CreateReplace
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      crds: CreateReplace
      remediation:
        retries: 3
    uninstall:
      keepHistory: false            
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        ingress:
          main:
            enabled: true
            hosts:
            - host: openspeedtest.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              traefik:
                enabled: true
                middlewares:
                - name: auth
              homepage:
                enabled: true
                group: "Utilities"
                icon: openspeedtest.png
                href: https://openspeedtest.${BASE_DOMAIN}
                widget:
                  enabled: false