# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openspeedtest
    namespace: openspeedtest
spec:
    interval: 15m
    chart:
      spec:
        chart: openspeedtest
        version: 11.5.2
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    driftDetection:
      mode: warn
    install:
      createNamespace: true
      crds: CreateReplace
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      crds: CreateReplace
      remediation:
        retries: 3
    uninstall:
      keepHistory: false            
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        ingress:
          main:
            enabled: true
            ingressClassName: internal
            annotations:
              nginx.ingress.kubernetes.io/auth-url: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/nginx
              nginx.ingress.kubernetes.io/auth-signin: https://auth.${BASE_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
              nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
              nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
            hosts:
            - host: openspeedtest.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              traefik:
                enabled: false
              homepage:
                enabled: true
                group: "Utilities"
                icon: openspeedtest.png
                href: https://openspeedtest.${BASE_DOMAIN}
                widget:
                  enabled: false