# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus
    namespace: prometheus
spec:
    interval: 15m
    chart:
      spec:
        chart: prometheus
        version: 22.5.3
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    driftDetection:
      mode: enabled
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: prometheus
    values:
        global:
            stopAll: false
        ingress:
          alertmanager:
            enabled: false
          main:
            enabled: true
            ingressClassName: internal
            hosts:
              - host: prometheus.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              traefik:
                enabled: false
       