# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pihole
    namespace: pihole
spec:
    interval: 15m
    chart:
      spec:
        chart: pihole
        version: 19.2.0
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            hosts:
              - host: pihole.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              traefik:
                enabled: true
                middlewares:
                - name: redirect-pihole
                  namespace: traefik
              homepage:
                enabled: true
                group: "Infrastructure"
                href: https://pihole.${BASE_DOMAIN}/admin
                widget:
                  type: pihole
                  custom:
                    url: http://pihole.pihole.svc.cluster.local:9089
                    key: ${HOMEPAGE_PIHOLE_KEY}
        persistence:
          config:
            volsync:
              - name: config
                type: restic
                credentials: s3
                dest:
                  enabled: true                          
                src:
                  enabled: true
        pihole:
          dnsServers:
            - ${BLOCKY_IP}
            - ${BLOCKY_IP}
          webPassword: ${PIHOLE_PASSWORD}
        service:
          dns:
            enabled: true
            loadBalancerIP: ${PIHOLE_IP}
            type: LoadBalancer