# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: clusterissuer
    namespace: clusterissuer
spec:
    interval: 15m
    chart:
        spec:
            chart: clusterissuer
            version: 9.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: clusterissuer
    values:
        clusterIssuer:
            ACME:
                - cfapikey: ""
                  cfapitoken: "${CLOUDFLARE_TOKEN}"
                  email: "${EMAIL}"
                  name: cloudflare-star-cert

                  server: https://acme-v02.api.letsencrypt.org/directory
                  type: cloudflare
            selfSigned:
                enabled: true
                name: selfsigned
