# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: portainer
    namespace: portainer
spec:
    interval: 15m
    chart:
      spec:
        chart: portainer
        version: 10.8.2
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: portainer
    values:
        global:
            stopAll: false
        TZ: America/Los_Angeles
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            hosts:
              - host: portainer.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
        persistence:
          cache:
            enabled: true
            mountPath: /.cache
            type: emptyDir
          data:
            volsync:
            - name: data
              type: restic
              credentials: s3
              dest:
                enabled: true                          
              src:
                enabled: true
