# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
    interval: 15m
    chart:
      spec:
       chart: jellyfin
       version: 20.6.30
       sourceRef:
         kind: HelmRepository
         name: truecharts
         namespace: flux-system
    driftDetection:
      mode: enabled
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: jellyfin
    values:
        global:
          stopAll: false
        TZ: America/Los_Angeles
        autodiscovery:
            enabled: true
        credentials:
          s3:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}"
            accessKey: "${S3_ID}"
            secretKey: "${S3_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            ingressClassName: internal
            hosts:
              - host: jellyfin.${BASE_DOMAIN}
            integrations:
              certManager:
                certificateIssuer: cloudflare-star-cert
                enabled: true
              homepage:
                enabled: true
                group: "Media"
                href: https://jellyfin.${BASE_DOMAIN}
                widget:
                  custom:
                    key: ${HOMEPAGE_JELLYFIN_KEY}
                    url: http://jellyfin.jellyfin.svc.cluster.local:8096
                    enableBlocks: "true"
                    enableNowPlaying: "true"
              traefik:
                enabled: false                    
        persistence:
          config:
            volsync:
              - name: config
                type: restic
                credentials: s3
                dest:
                  enabled: true                          
                src:
                  enabled: true
                  cacheCapacity: 10Gi
                trigger:
                  schedule: 30 0 * * *
          media:
            enabled: true
            path: "${JELLYFIN_MEDIA_PATH}"
            mountPath: "/media"
            server: "${SCALE_SERVER_IP}"
            type: nfs
        service:
          main:
            enabled: true
            loadBalancerIP: ${JELLYFIN_IP}    
            type: LoadBalancer
        resources:
          limits:
            nvidia.com/gpu: 1
        workload:
          main:
            podSpec:
              runtimeClassName: "nvidia"
              containers:
                main:
                  resources:
                    limits:
                      nvidia.com/gpu: 1
